import { z } from "./zod.js";
import {
  OpenAPIRegistry,
  OpenApiGeneratorV3,
} from "@asteasolutions/zod-to-openapi";

export const registry = new OpenAPIRegistry();

// ==============================================================================
// Standard RFC 9457 Problem Details Schemas
// ==============================================================================

export const BaseProblemSchema = z
  .object({
    type: z.string().openapi({
      description: "Relative URI identifier of the specific problem type (machine-readable code)",
      example: "/errors/validation-failed",
    }),
    title: z.string().openapi({
      description: "Short human-readable developer summary of the problem type",
      example: "Validation Failed",
    }),
    status: z.number().int().openapi({
      description: "The HTTP status code generated by the origin server",
      example: 422,
    }),
    detail: z.string().optional().openapi({
      description: "Human-readable explanation specific to this occurrence of the problem",
      example: "One or more request parameters failed validation schema checks.",
    }),
    instance: z.string().optional().openapi({
      description: "A URI reference that identifies the specific occurrence of the problem",
      example: "/api/v1/areas?level=INVALID",
    }),
    requestId: z.string().openapi({
      description: "Authoritative request correlation ID (UUIDv7) for telemetry tracing",
      example: "0191eb45-8f67-73d8-9db8-bc234a9e51c8",
    }),
    params: z.record(z.unknown()).optional().openapi({
      description: "Structured machine-readable parameters for localized client error rendering",
    }),
  })
  .openapi("BaseProblem");

export const ValidationProblemSchema = BaseProblemSchema.extend({
  type: z.literal("/errors/validation-failed"),
  status: z.literal(422),
  errors: z.array(
    z.object({
      path: z.string().openapi({ example: "level" }),
      code: z.string().openapi({ example: "invalid_enum_value" }),
      message: z.string().optional().openapi({ example: "Invalid enum value" }),
      params: z.record(z.unknown()).optional(),
    })
  ).openapi({ description: "Array of validation issues per field" }),
}).openapi("ValidationProblem");

export const NotFoundProblemSchema = BaseProblemSchema.extend({
  type: z.literal("/errors/not-found"),
  status: z.literal(404),
}).openapi("NotFoundProblem");

export const ForbiddenProblemSchema = BaseProblemSchema.extend({
  type: z.literal("/errors/forbidden"),
  status: z.literal(403),
}).openapi("ForbiddenProblem");

export const UnauthenticatedProblemSchema = BaseProblemSchema.extend({
  type: z.literal("/errors/unauthenticated"),
  status: z.literal(401),
}).openapi("UnauthenticatedProblem");

export const ConflictProblemSchema = BaseProblemSchema.extend({
  type: z.string(),
  status: z.literal(409),
}).openapi("ConflictProblem");

export const InternalProblemSchema = BaseProblemSchema.extend({
  type: z.literal("/errors/internal"),
  status: z.literal(500),
}).openapi("InternalProblem");

// Register common RFC 9457 components
registry.register("BaseProblem", BaseProblemSchema);
registry.register("ValidationProblem", ValidationProblemSchema);
registry.register("NotFoundProblem", NotFoundProblemSchema);
registry.register("ForbiddenProblem", ForbiddenProblemSchema);
registry.register("UnauthenticatedProblem", UnauthenticatedProblemSchema);
registry.register("ConflictProblem", ConflictProblemSchema);
registry.register("InternalProblem", InternalProblemSchema);

// Security schemes (Session Cookie for Better Auth)
registry.registerComponent("securitySchemes", "SessionCookie", {
  type: "apiKey",
  in: "cookie",
  name: "settly_session",
  description: "Better Auth HTTP-only secure session cookie",
});

/**
 * Compiles all registered routes and schemas into an OpenAPI 3.0.3 specification object.
 */
export function generateOpenApiDocument() {
  const generator = new OpenApiGeneratorV3(registry.definitions);

  return generator.generateDocument({
    openapi: "3.0.3",
    info: {
      title: "Settly Core API",
      version: "1.0.0",
      description:
        "Authoritative HTTP API contract for the Settly real estate platform. Implements RFC 9457 error taxonomy, strict validation, and bilingual domain entities.",
    },
    servers: [
      {
        url: "http://localhost:4000",
        description: "Local development server",
      },
    ],
  });
}
