/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List geographic areas
         * @description Retrieve the hierarchical list of areas in Egypt (governorates, cities, districts, compounds). Supports filtering by administrative level and parent area.
         */
        get: {
            parameters: {
                query?: {
                    level?: "GOVERNORATE" | "CITY" | "DISTRICT" | "COMPOUND";
                    parentId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collection of geographic areas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Array of geographic areas matching query criteria */
                            items: components["schemas"]["AreaItem"][];
                        };
                    };
                };
                /** @description Validation failed for query parameters */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/areas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an area by ID
         * @description Retrieve detailed area record by its UUIDv7 identifier.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bare area resource */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AreaItem"];
                    };
                };
                /** @description Area not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["NotFoundProblem"];
                    };
                };
                /** @description Invalid UUID format */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/areas/{identifier}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get market insights and telemetry for an area
         * @description Retrieve price per m² averages, historical trend telemetry, compound counts, and property distributions for an area by slug or UUID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Area market insights and historical trend telemetry */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AreaInsightsResponse"];
                    };
                };
                /** @description Area not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["NotFoundProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published properties
         * @description Returns paginated list of published and reserved properties for public browsing.
         */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of properties */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a draft property listing (P1) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateProperty"];
                };
            };
            responses: {
                /** @description Draft property created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ForbiddenProblem"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get property details by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyResponse"];
                    };
                };
                /** @description Property not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["NotFoundProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Hard-delete a never-published DRAFT listing (Decision #42) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Draft listing deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ForbiddenProblem"];
                    };
                };
                /** @description Cannot hard-delete published listing */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ConflictProblem"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a property listing with two-tier moderation (P6) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateProperty"];
                };
            };
            responses: {
                /** @description Property updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ForbiddenProblem"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["NotFoundProblem"];
                    };
                };
                /** @description Conflict / Terminal state */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ConflictProblem"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/properties/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get property details by SEO slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyResponse"];
                    };
                };
                /** @description Property not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["NotFoundProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit draft listing for publication review (P2) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property submitted for review */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyResponse"];
                    };
                };
                /** @description Forbidden or agent not verified */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ForbiddenProblem"];
                    };
                };
                /** @description Invalid transition */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ConflictProblem"];
                    };
                };
                /** @description Missing required fields or <3 images */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{id}/resubmit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resubmit rejected listing for review (P5) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property resubmitted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyResponse"];
                    };
                };
                /** @description Invalid transition */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ConflictProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a published listing (P7) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property archived */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyResponse"];
                    };
                };
                /** @description Active reservation prevents archiving */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ConflictProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{id}/sell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Offline-sale escape hatch for published property (P11) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ActionReason"];
                };
            };
            responses: {
                /** @description Property marked as SOLD offline */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{id}/mark-sold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm sale of reserved listing (P9) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property marked as SOLD */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{id}/relist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Relist archived listing back to draft (P14) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property relisted to DRAFT */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/properties/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve listing for publication (P3) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property published */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/properties/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject listing from moderation queue (P4) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ActionReason"];
                };
            };
            responses: {
                /** @description Property rejected */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/properties/{id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend a listing immediately (P12) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ActionReason"];
                };
            };
            responses: {
                /** @description Property suspended */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/properties/{id}/unsuspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unsuspend listing (P13) */
        post: {
            parameters: {
                query?: {
                    target?: "PUBLISHED" | "ARCHIVED";
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property unsuspended */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current agent listings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of agent properties */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/amenities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List property amenities
         * @description Retrieve controlled vocabulary of property amenities, optionally filtered by category.
         */
        get: {
            parameters: {
                query?: {
                    category?: "INTERIOR" | "EXTERIOR" | "FACILITY" | "SECURITY" | "LOCATION";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of amenities */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AmenityListResponse"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblem"];
                    };
                };
            };
        };
        put?: never;
        /** Create property amenity (Admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateAmenity"];
                };
            };
            responses: {
                /** @description Amenity created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AmenityItem"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ForbiddenProblem"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authorize direct media upload
         * @description Issues signed Cloudinary upload parameters for direct client upload per STORAGE.md Section 3.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthorizeUpload"];
                };
            };
            responses: {
                /** @description Signed upload instructions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthorizeUploadResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{assetId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalize direct upload
         * @description Binds uploaded provider asset to property record per STORAGE.md Section 3.
         */
        post: {
            parameters: {
                query?: {
                    propertyId?: string;
                };
                header?: never;
                path: {
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CompleteUpload"];
                };
            };
            responses: {
                /** @description Upload finalized */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompleteUploadResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description Retrieve the authenticated user's profile, role, verification status, and settings.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Authenticated user profile data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfileResponse"];
                    };
                };
                /** @description Unauthenticated request (missing or invalid session cookie) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Forbidden (account suspended or banned) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ForbiddenProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update current user profile
         * @description Update display name or language preference (en / ar) for the current user.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserProfile"];
                };
            };
            responses: {
                /** @description Updated user profile data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfileResponse"];
                    };
                };
                /** @description Unauthenticated request */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Validation error in request payload */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblem"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/me/agent-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get agent profile for current user
         * @description Retrieve broker license, brokerage affiliation, and biographies. Requires AGENT or ADMIN role.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agent profile details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentProfileResponse"];
                    };
                };
                /** @description Unauthenticated request */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Forbidden: user does not hold AGENT or ADMIN role */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ForbiddenProblem"];
                    };
                };
                /** @description Agent profile record not yet created */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["NotFoundProblem"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create or update agent profile
         * @description Register or update real estate license and brokerage profile details. Requires AGENT or ADMIN role.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateOrUpdateAgentProfile"];
                };
            };
            responses: {
                /** @description Saved agent profile details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentProfileResponse"];
                    };
                };
                /** @description Unauthenticated request */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Forbidden: user does not hold AGENT or ADMIN role */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ForbiddenProblem"];
                    };
                };
                /** @description Validation error in request payload */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List agent verification queue (Admin only)
         * @description Returns registered agent profiles for moderation and verification review.
         */
        get: {
            parameters: {
                query?: {
                    verified?: "true" | "false";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of agent profiles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentListResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Forbidden (Admin role required) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ForbiddenProblem"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get agent profile details for review (Admin only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agent profile details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentListItem"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ForbiddenProblem"];
                    };
                };
                /** @description Agent profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["NotFoundProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/agents/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve or revoke agent verification (Admin only)
         * @description Updates agent verification status and records an immutable AuditLog entry.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AgentVerificationInput"];
                };
            };
            responses: {
                /** @description Agent verification updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentListItem"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ForbiddenProblem"];
                    };
                };
                /** @description Agent profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["NotFoundProblem"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register or update FCM device token for push notifications
         * @description Associates a Web Push or Mobile FCM token with the authenticated user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserDeviceRegistrationInput"];
                };
            };
            responses: {
                /** @description Device registered successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDeviceResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/devices/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deregister FCM device token
         * @description Removes push notification token upon user logout or notification revocation.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Device deregistered successfully (no content) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["UnauthenticatedProblem"];
                    };
                };
                /** @description Device token not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["NotFoundProblem"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare multiple properties
         * @description Retrieve side-by-side architectural and financial specifications for between 2 and 4 residences.
         */
        get: {
            parameters: {
                query: {
                    ids: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Comparison specifications matrix */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompareResponse"];
                    };
                };
                /** @description Validation failed (e.g. fewer than 2 or more than 4 properties specified) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/market-pulse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get prime Egyptian real estate market telemetry and macroeconomic indicators
         * @description Returns live sovereign economic indicators, currency benchmarks (USD/EGP, EUR/EGP), corridor annual capital appreciation rates, and quarterly real estate transaction volume.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Macroeconomic telemetry and corridor price benchmarks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarketPulseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List verified certified advisors and brokers
         * @description Retrieve the public directory of certified real estate advisors with licensing transparency and active listing counts.
         */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    brokerage?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collection of certified advisors */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentDirectoryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get public profile and active exclusive listings for an advisor
         * @description Retrieve verified broker profile, FRA/REA registration badges, biography, and active published residences.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Advisor public profile and published listings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentProfileDetailResponse"];
                    };
                };
                /** @description Advisor not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["NotFoundProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BaseProblem: {
            /**
             * @description Relative URI identifier of the specific problem type (machine-readable code)
             * @example /errors/validation-failed
             */
            type: string;
            /**
             * @description Short human-readable developer summary of the problem type
             * @example Validation Failed
             */
            title: string;
            /**
             * @description The HTTP status code generated by the origin server
             * @example 422
             */
            status: number;
            /**
             * @description Human-readable explanation specific to this occurrence of the problem
             * @example One or more request parameters failed validation schema checks.
             */
            detail?: string;
            /**
             * @description A URI reference that identifies the specific occurrence of the problem
             * @example /api/v1/areas?level=INVALID
             */
            instance?: string;
            /**
             * @description Authoritative request correlation ID (UUIDv7) for telemetry tracing
             * @example 0191eb45-8f67-73d8-9db8-bc234a9e51c8
             */
            requestId: string;
            /** @description Structured machine-readable parameters for localized client error rendering */
            params?: {
                [key: string]: unknown;
            };
        };
        ValidationProblem: components["schemas"]["BaseProblem"] & {
            /** @enum {string} */
            type?: "/errors/validation-failed";
            /** @enum {number} */
            status?: 422;
            /** @description Array of validation issues per field */
            errors: {
                /** @example level */
                path: string;
                /** @example invalid_enum_value */
                code: string;
                /** @example Invalid enum value */
                message?: string;
                params?: {
                    [key: string]: unknown;
                };
            }[];
        };
        NotFoundProblem: components["schemas"]["BaseProblem"] & {
            /** @enum {string} */
            type?: "/errors/not-found";
            /** @enum {number} */
            status?: 404;
        };
        ForbiddenProblem: components["schemas"]["BaseProblem"] & {
            /** @enum {string} */
            type?: "/errors/forbidden";
            /** @enum {number} */
            status?: 403;
        };
        UnauthenticatedProblem: components["schemas"]["BaseProblem"] & {
            /** @enum {string} */
            type?: "/errors/unauthenticated";
            /** @enum {number} */
            status?: 401;
        };
        ConflictProblem: components["schemas"]["BaseProblem"] & {
            type?: string;
            /** @enum {number} */
            status?: 409;
        };
        InternalProblem: components["schemas"]["BaseProblem"] & {
            /** @enum {string} */
            type?: "/errors/internal";
            /** @enum {number} */
            status?: 500;
        };
        AgentRegistrationInput: {
            /**
             * @description Official Egyptian Real Estate Regulatory Authority license number
             * @example EGY-RE-2026-9912
             */
            licenseNumber: string;
            /**
             * @description Registered brokerage or agency name
             * @example Sovereign Cairo Partners
             */
            brokerageName: string;
            /**
             * @description English biography and specialties
             * @example Specialist in New Cairo and Golden Square luxury villas.
             */
            bioEn?: string;
            /**
             * @description Arabic biography and specialties
             * @example متخصص في فلل القاهرة الجديدة والمربع الذهبي.
             */
            bioAr?: string;
        };
        AgentVerificationInput: {
            /**
             * @description Verification decision: true to approve, false to revoke/reject
             * @example true
             */
            verified: boolean;
            /**
             * @description Administrative rationale or review notes
             * @example License verified against Egyptian Real Estate Authority registry.
             */
            notes?: string;
        };
        AgentListItem: {
            /**
             * Format: uuid
             * @description Agent profile UUIDv7
             */
            id: string;
            /** @description User ID FK */
            userId: string;
            licenseNumber: string;
            brokerageName: string;
            bioEn?: string | null;
            bioAr?: string | null;
            isVerified: boolean;
            /** Format: date-time */
            verifiedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            user: {
                id: string;
                name: string;
                /** Format: email */
                email: string;
                /** Format: uri */
                image?: string | null;
            };
        };
        AgentListResponse: {
            /** @description Array of agent profiles */
            items: components["schemas"]["AgentListItem"][];
        };
        UserDeviceRegistrationInput: {
            /**
             * @description FCM (Firebase Cloud Messaging) device or browser push token
             * @example fcm_token_sample_abc1234567890
             */
            token: string;
            /**
             * @description Target platform for push notification dispatch
             * @example WEB
             * @enum {string}
             */
            platform: "IOS" | "ANDROID" | "WEB";
        };
        UserDeviceResponse: {
            /** Format: uuid */
            id: string;
            userId: string;
            token: string;
            platform: string;
            /** Format: date-time */
            createdAt: string;
        };
        AreaItem: {
            /**
             * Format: uuid
             * @description Unique Area UUIDv7 identifier
             * @example 0191eb45-8f67-73d8-9db8-bc234a9e51c8
             */
            id: string;
            /**
             * @description URL-friendly unique slug identifier
             * @example new-cairo
             */
            slug: string;
            /**
             * @description Canonical English area name
             * @example New Cairo
             */
            nameEn: string;
            /**
             * @description Canonical Arabic area name
             * @example القاهرة الجديدة
             */
            nameAr: string;
            /**
             * @description Alternative aliases or colloquial names for search autocomplete matching
             * @example [
             *       "Fifth Settlement",
             *       "التجمع الخامس"
             *     ]
             */
            aliases: string[];
            /**
             * Format: uuid
             * @description Parent area UUIDv7 in the geographic hierarchy (e.g. Governorate for a City)
             * @example null
             */
            parentId: string | null;
            /**
             * @description Geographic administrative level within the Egyptian real estate taxonomy
             * @example DISTRICT
             * @enum {string}
             */
            level: "GOVERNORATE" | "CITY" | "DISTRICT" | "COMPOUND";
            /**
             * @description Optional GeoJSON boundary geometry string for map visualization
             * @example null
             */
            boundaryGeoJson: string | null;
            /**
             * @description Geographic latitude coordinate of the area centroid
             * @example 30.0244
             */
            centerLat: number | null;
            /**
             * @description Geographic longitude coordinate of the area centroid
             * @example 31.4921
             */
            centerLng: number | null;
            /**
             * Format: date-time
             * @description ISO 8601 creation timestamp
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description ISO 8601 update timestamp
             */
            updatedAt: string;
        };
        AreaInsightsResponse: {
            area: components["schemas"]["AreaItem"];
            metrics: {
                /** @example 12 */
                activePropertiesCount: number;
                /** @example 4 */
                compoundsCount: number;
                /** @example 68500 */
                averagePricePerSqm: number;
                /** @example 12500000 */
                minPrice: string;
                /** @example 45000000 */
                maxPrice: string;
                /** @example 8.4 */
                averageYieldPercentage: number;
                /** @example 28.5 */
                capitalAppreciationYoY: number;
            };
            /**
             * @description Inventory count grouped by property type
             * @example {
             *       "VILLA": 8,
             *       "APARTMENT": 4
             *     }
             */
            propertyTypesDistribution: {
                [key: string]: number;
            };
            /** @description Quarterly historical price per sqm telemetry */
            historicalPriceTrend: {
                /** @example Q1 2025 */
                period: string;
                /** @example 52000 */
                avgPricePerSqm: number;
                /** @example 14.2 */
                changePercent: number;
            }[];
        };
        /** @enum {string} */
        PropertyType: "APARTMENT" | "VILLA" | "DUPLEX" | "PENTHOUSE" | "TOWNHOUSE" | "CHALET";
        /** @enum {string} */
        ListingIntent: "SALE" | "RENT";
        /** @enum {string|null} */
        RentalPeriod: "MONTHLY" | "YEARLY" | null;
        /** @enum {string} */
        PropertyStatus: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "RESERVED" | "SOLD" | "RENTED" | "ARCHIVED" | "SUSPENDED";
        PropertyImage: {
            /**
             * Format: uuid
             * @example 0191eb45-8f67-73d8-9db8-bc234a9e51c8
             */
            id: string;
            /**
             * Format: uuid
             * @example 0191eb45-8f67-73d8-9db8-bc234a9e51c9
             */
            propertyId: string;
            /** @example settly/properties/villa-1 */
            cloudinaryPublicId: string;
            /**
             * Format: uri
             * @example https://res.cloudinary.com/dmzcnnxzp/image/upload/v1/settly/properties/villa-1.jpg
             */
            url: string;
            captionEn?: string | null;
            captionAr?: string | null;
            /** @default false */
            isCover: boolean;
            /** @default 0 */
            order: number;
            /** Format: date-time */
            createdAt: string;
        };
        AmenityItem: {
            /**
             * Format: uuid
             * @example 0191eb45-8f67-73d8-9db8-bc234a9e51c8
             */
            id: string;
            /** @example private-pool */
            slug: string;
            /** @example Private Pool */
            nameEn: string;
            /** @example حمام سباحة خاص */
            nameAr: string;
            /** @example pool */
            icon: string | null;
            /**
             * @example EXTERIOR
             * @enum {string}
             */
            category: "INTERIOR" | "EXTERIOR" | "FACILITY" | "SECURITY" | "LOCATION";
            /**
             * Format: date-time
             * @example 2026-09-05T12:00:00Z
             */
            createdAt: string;
        };
        PropertyAgentSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            image: string | null;
            licenseNumber?: string;
            brokerageName?: string;
            /** @default false */
            isVerified: boolean;
        };
        PropertyPriceHistory: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            propertyId: string;
            /**
             * @description Price in EGP piastres as a numeric string
             * @example 1500000000
             */
            price: string;
            /** Format: date-time */
            changedAt: string;
            changedById: string | null;
        };
        PropertyResponse: {
            /**
             * Format: uuid
             * @example 0191eb45-8f67-73d8-9db8-bc234a9e51c8
             */
            id: string;
            /** @example 0191eb45-8f67-73d8-9db8-bc234a9e51c0 */
            agentId: string;
            /**
             * Format: uuid
             * @example 0191eb45-8f67-73d8-9db8-bc234a9e51c1
             */
            areaId: string;
            /** @example signature-lake-view-villa-0191eb45 */
            slug: string;
            titleEn: string | null;
            titleAr: string | null;
            descriptionEn: string | null;
            descriptionAr: string | null;
            propertyType: components["schemas"]["PropertyType"];
            listingIntent: components["schemas"]["ListingIntent"];
            /**
             * @description Price in EGP piastres (stringified BigInt)
             * @example 1500000000
             */
            price: string;
            rentalPeriod: components["schemas"]["RentalPeriod"];
            bedrooms: number;
            bathrooms: number;
            areaSqm: number;
            status: components["schemas"]["PropertyStatus"];
            featured: boolean;
            latitude: number;
            longitude: number;
            /** Format: date-time */
            publishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @default [] */
            images: components["schemas"]["PropertyImage"][];
            /** @default [] */
            amenities: components["schemas"]["AmenityItem"][];
            area?: components["schemas"]["AreaItem"];
            agent?: components["schemas"]["PropertyAgentSummary"];
            priceHistories?: components["schemas"]["PropertyPriceHistory"][];
        };
        PropertyListResponse: {
            items: components["schemas"]["PropertyResponse"][];
            nextCursor?: string | null;
            totalCount?: number;
        };
        CreateProperty: {
            titleEn?: string;
            titleAr?: string;
            descriptionEn?: string;
            descriptionAr?: string;
            propertyType: components["schemas"]["PropertyType"];
            listingIntent: components["schemas"]["ListingIntent"];
            price: string | number;
            rentalPeriod?: components["schemas"]["RentalPeriod"];
            bedrooms: number;
            bathrooms: number;
            areaSqm: number;
            latitude: number;
            longitude: number;
            /** Format: uuid */
            areaId: string;
            amenityIds?: string[];
        };
        UpdateProperty: {
            titleEn?: string;
            titleAr?: string;
            descriptionEn?: string;
            descriptionAr?: string;
            propertyType?: components["schemas"]["PropertyType"];
            listingIntent?: components["schemas"]["ListingIntent"];
            price?: string | number;
            rentalPeriod?: components["schemas"]["RentalPeriod"];
            bedrooms?: number;
            bathrooms?: number;
            areaSqm?: number;
            latitude?: number;
            longitude?: number;
            /** Format: uuid */
            areaId?: string;
            amenityIds?: string[];
        };
        ActionReason: {
            /** @example Photos do not meet quality guidelines */
            reason: string;
        };
        AmenityListResponse: {
            items: components["schemas"]["AmenityItem"][];
        };
        CreateAmenity: {
            slug: string;
            nameEn: string;
            nameAr: string;
            icon?: string;
            /**
             * @default INTERIOR
             * @enum {string}
             */
            category: "INTERIOR" | "EXTERIOR" | "FACILITY" | "SECURITY" | "LOCATION";
        };
        AuthorizeUploadResponse: {
            /** Format: uuid */
            assetId: string;
            /** @enum {string} */
            provider: "cloudinary";
            /** Format: uri */
            uploadUrl: string;
            params: {
                [key: string]: unknown;
            };
            constraints: {
                maxBytes: number;
                allowedTypes: string[];
            };
        };
        AuthorizeUpload: {
            /**
             * @default property_image
             * @enum {string}
             */
            kind: "property_image" | "document" | "avatar";
            /** Format: uuid */
            propertyId?: string;
            contentType: string;
            byteSize: number;
            filename: string;
        };
        CompleteUploadResponse: {
            /** Format: uuid */
            assetId: string;
            /** @enum {string} */
            status: "READY" | "PROCESSING" | "FAILED";
            image?: components["schemas"]["PropertyImage"];
        };
        CompleteUpload: {
            providerRef: string;
            /** Format: uri */
            url: string;
            cloudinaryPublicId: string;
            captionEn?: string;
            captionAr?: string;
            isCover?: boolean;
        };
        UserProfileResponse: {
            /**
             * @description Unique user identifier (canonical Better Auth user id)
             * @example 0191eb45-8f67-73d8-9db8-bc234a9e51c8
             */
            id: string;
            /**
             * @description Full user display name
             * @example Tarek Mansour
             */
            name: string;
            /**
             * Format: email
             * @description Primary registered user email address
             * @example tarek.mansour@example.com
             */
            email: string;
            /**
             * @description Whether the email address has passed verification (Decision #38)
             * @example true
             */
            emailVerified: boolean;
            /**
             * @description Phone in E.164 format; null only for Google accounts that have not completed their profile (#60, #106). Never public
             * @example +201001234567
             */
            phone: string | null;
            /**
             * @description Optional profile avatar URL
             * @example null
             */
            image: string | null;
            /**
             * @description User role within Settly authorization matrix (AUTH.md §7)
             * @example USER
             * @enum {string}
             */
            role: "USER" | "AGENT" | "ADMIN";
            /**
             * @description Preferred UI/notification locale (en or ar) per Decision #39
             * @example en
             * @enum {string|null}
             */
            preferredLocale: "en" | "ar" | null;
            /**
             * Format: date-time
             * @description Account creation ISO 8601 timestamp
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Account modification ISO 8601 timestamp
             */
            updatedAt: string;
        };
        UpdateUserProfile: {
            /**
             * @description Updated user display name
             * @example Tarek H. Mansour
             */
            name?: string;
            /**
             * @description Updated language preference
             * @example ar
             * @enum {string}
             */
            preferredLocale?: "en" | "ar";
            /**
             * @description Phone number, international format; normalised to E.164 (#60)
             * @example +201001234567
             */
            phone?: string;
        };
        AgentProfileResponse: {
            /**
             * @description Agent profile record identifier
             * @example 0191eb45-8f67-73d8-9db8-bc234a9e51c8
             */
            id: string;
            /**
             * @description Foreign key reference to Better Auth User
             * @example 0191eb45-8f67-73d8-9db8-bc234a9e51c8
             */
            userId: string;
            /**
             * @description Official Egyptian real estate brokerage license number
             * @example EGY-RE-2026-9042
             */
            licenseNumber: string;
            /**
             * @description Optional brokerage or agency commercial name
             * @example Sotheby's International Realty Cairo
             */
            brokerageName: string | null;
            /**
             * @description English biographical overview and specialties
             * @example Specialist in luxury residential properties across New Cairo and Golden Square.
             */
            bioEn: string | null;
            /**
             * @description Arabic biographical overview and specialties
             * @example خبير في العقارات الفاخرة بالقاهرة الجديدة والمربع الذهبي.
             */
            bioAr: string | null;
            /**
             * @description Whether the agent's credentials have been verified by Settly compliance
             * @example true
             */
            isVerified: boolean;
            /**
             * Format: date-time
             * @description Timestamp when verification was approved
             */
            verifiedAt: string | null;
            /**
             * Format: date-time
             * @description Agent profile creation ISO 8601 timestamp
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Agent profile update ISO 8601 timestamp
             */
            updatedAt: string;
        };
        CreateOrUpdateAgentProfile: {
            /**
             * @description Official real estate brokerage license ID
             * @example EGY-RE-2026-9042
             */
            licenseNumber: string;
            /**
             * @description Commercial brokerage or agency name if affiliated
             * @example Sotheby's International Realty Cairo
             */
            brokerageName?: string | null;
            /** @description English biography */
            bioEn?: string | null;
            /** @description Arabic biography */
            bioAr?: string | null;
        };
        CompareItem: {
            id: string;
            slug: string;
            titleEn: string | null;
            titleAr: string | null;
            propertyType: string;
            listingIntent: string;
            price: string;
            rentalPeriod: string | null;
            bedrooms: number;
            bathrooms: number;
            areaSqm: number;
            pricePerSqm: number;
            latitude: number;
            longitude: number;
            coverImage: string | null;
            images: string[];
            area: {
                id: string;
                slug: string;
                nameEn: string;
                nameAr: string;
            };
            amenities: {
                id: string;
                slug: string;
                nameEn: string;
                nameAr: string;
                category: string;
            }[];
        };
        CompareResponse: {
            /** @description Array of compared residences with aligned specifications */
            items: components["schemas"]["CompareItem"][];
            /** @description Number of properties compared (2 to 4) */
            count: number;
        };
        MarketPulseResponse: {
            currencyRates: {
                usdEgp: {
                    /** @example 48.85 */
                    official: number;
                    /** @example 49.1 */
                    market: number;
                    /** @example -0.15 */
                    change24h: number;
                };
                eurEgp: {
                    /** @example 48.85 */
                    official: number;
                    /** @example 49.1 */
                    market: number;
                    /** @example -0.15 */
                    change24h: number;
                };
            };
            macroIndicators: {
                /** @example 25.7 */
                inflationRate: number;
                /** @example 8.8 */
                primeYieldAverage: number;
                /** @example 6.2 */
                quarterlyAppreciationRate: number;
                /** @example 28.4 */
                annualAppreciationRate: number;
                /** @example 145000000000 */
                quarterlyVolumeEgp: string;
            };
            corridorsBenchmark: {
                /** @example East Cairo / New Cairo & Katameya */
                corridor: string;
                /** @example 72500 */
                avgPricePerSqm: number;
                /** @example 31.4 */
                appreciationYoY: number;
                /** @example 8.9 */
                rentalYield: number;
            }[];
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of telemetry snapshot
             */
            lastUpdated: string;
        };
        AgentDirectoryItem: {
            /** @description AgentProfile UUID */
            id: string;
            /** @description User ID */
            userId: string;
            /** @example Hana K. */
            name: string;
            /** @example /images/hana.jpg */
            image: string | null;
            /** @example CAI-2024-8841 */
            licenseNumber: string;
            /** @example Sotheby's International Realty Egypt */
            brokerageName: string | null;
            /** @example Prime Cairo & Katameya advisory specialist. */
            bioEn: string | null;
            /** @example مستشارة عقارية متخصصة في عقارات التجمع الخامس والقطامية. */
            bioAr: string | null;
            /** @example true */
            isVerified: boolean;
            /** Format: date-time */
            verifiedAt: string | null;
            /** @example 6 */
            activeListingsCount: number;
            /**
             * @example [
             *       "New Cairo",
             *       "Katameya Dunes"
             *     ]
             */
            primaryCorridors: string[];
        };
        AgentDirectoryResponse: {
            items: components["schemas"]["AgentDirectoryItem"][];
            /** @example 1 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 12 */
            limit: number;
        };
        AgentProfileDetailResponse: {
            agent: components["schemas"]["AgentDirectoryItem"];
            listings: {
                id: string;
                slug: string;
                titleEn: string | null;
                titleAr: string | null;
                propertyType: string;
                price: string;
                bedrooms: number;
                bathrooms: number;
                areaSqm: number;
                coverImage: string | null;
                area: {
                    nameEn: string;
                    nameAr: string;
                    slug: string;
                };
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
