-- Decision #105 and BUSINESS_RULES §5: Reconcile deposit enums
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "AttemptStatus" ADD VALUE IF NOT EXISTS 'ABANDONED';
ALTER TYPE "AttemptStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
ALTER TYPE "RefundStatus" ADD VALUE IF NOT EXISTS 'SUCCEEDED';
